using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace PSProcessMonitor
{
    public enum FilesystemOperation : short
    {
        VolumeDismount = 0,
        IRP_MJ_VOLUME_DISMOUNT = 0,
        VolumeMount = 1,
        IRP_MJ_VOLUME_MOUNT = 1,
        FASTIO_MDL_WRITE_COMPLETE = 2,
        WriteFile2 = 3,
        FASTIO_PREPARE_MDL_WRITE = 3,
        FASTIO_MDL_READ_COMPLETE = 4,
        ReadFile2 = 5,
        FASTIO_MDL_READ = 5,
        QueryOpen = 6,
        FASTIO_NETWORK_QUERY_OPEN = 6,
        FASTIO_CHECK_IF_POSSIBLE = 7,
        IRP_MJ_12 = 8,
        IRP_MJ_11 = 9,
        IRP_MJ_10 = 10,
        IRP_MJ_9 = 11,
        IRP_MJ_8 = 12,
        FASTIO_NOTIFY_STREAM_FO_CREATION = 13,
        FASTIO_RELEASE_FOR_CC_FLUSH = 14,
        FASTIO_ACQUIRE_FOR_CC_FLUSH = 15,
        FASTIO_RELEASE_FOR_MOD_WRITE = 16,
        FASTIO_ACQUIRE_FOR_MOD_WRITE = 17,
        FASTIO_RELEASE_FOR_SECTION_SYNCHRONIZATION = 18,
        CreateFileMapping = 19,
        FASTIO_ACQUIRE_FOR_SECTION_SYNCHRONIZATION = 19,
        CreateFile = 20,
        IRP_MJ_CREATE = 20,
        CreatePipe = 21,
        IRP_MJ_CREATE_NAMED_PIPE = 21,
        IRP_MJ_CLOSE = 22,
        ReadFile = 23,
        IRP_MJ_READ = 23,
        WriteFile = 24,
        IRP_MJ_WRITE = 24,
        QueryInformationFile = 25,
        IRP_MJ_QUERY_INFORMATION = 25,
        SetInformationFile = 26,
        IRP_MJ_SET_INFORMATION = 26,
        QueryEAFile = 27,
        IRP_MJ_QUERY_EA = 27,
        SetEAFile = 28,
        IRP_MJ_SET_EA = 28,
        FlushBuffersFile = 29,
        IRP_MJ_FLUSH_BUFFERS = 29,
        QueryVolumeInformation = 30,
        IRP_MJ_QUERY_VOLUME_INFORMATION = 30,
        SetVolumeInformation = 31,
        IRP_MJ_SET_VOLUME_INFORMATION = 31,
        DirectoryControl = 32,
        IRP_MJ_DIRECTORY_CONTROL = 32,
        FileSystemControl = 33,
        IRP_MJ_FILE_SYSTEM_CONTROL = 33,
        DeviceIoControl = 34,
        IRP_MJ_DEVICE_CONTROL = 34,
        InternalDeviceIoControl = 35,
        IRP_MJ_INTERNAL_DEVICE_CONTROL = 35,
        Shutdown = 36,
        IRP_MJ_SHUTDOWN = 36,
        LockUnlockFile = 37,
        IRP_MJ_LOCK_CONTROL = 37,
        CloseFile = 38,
        IRP_MJ_CLEANUP = 38,
        CreateMailSlot = 39,
        IRP_MJ_CREATE_MAILSLOT = 39,
        QuerySecurityFile = 40,
        IRP_MJ_QUERY_SECURITY = 40,
        SetSecurityFile = 41,
        IRP_MJ_SET_SECURITY = 41,
        Power = 42,
        IRP_MJ_POWER = 42,
        SystemControl = 43,
        IRP_MJ_SYSTEM_CONTROL = 43,
        DeviceChange = 44,
        IRP_MJ_DEVICE_CHANGE = 44,
        QueryFileQuota = 45,
        IRP_MJ_QUERY_QUOTA = 45,
        SetFileQuota = 46,
        IRP_MJ_SET_QUOTA = 46,
        PlugAndPlay = 47,
        IRP_MJ_PNP = 47,
    }
}